## Core python programming 

In [1]:
# =============TYPES OF VARIABLES ( INT , FLOAT, STRING, BOOL)================

# int - 
x=2

In [2]:
x

2

In [3]:
type(x)

int

In [4]:
# float -
y = 4.6

In [5]:
y

4.6

In [6]:
type(y)

float

In [7]:
# string - 
z = 'hello'

In [8]:
z

'hello'

In [9]:
z1 = "hi"

In [10]:
z1
print(z1)

hi


In [11]:
# bool // logical -
g = 'True'

In [12]:
g

'True'

In [13]:
i = "False"

In [14]:
i

'False'

In [15]:
a2=45

In [16]:
b2=56

In [17]:
print(a2)
print(b2)

45
56


In [18]:
a2
b2

56

In [19]:
# ================== USING VARIABLES =======================

# Arithmetic -
A = 10
B = 5

In [20]:
C = A + B

In [21]:
D = B/A

In [22]:
E = A*B

In [23]:
F = B-A

In [24]:
C

15

In [25]:
D

0.5

In [26]:
E

50

In [27]:
F

-5

In [28]:
# why is it better to use print() // (ANS) - all o/p will display one time 
print(C)
print(D)
print(E)
print(F)

15
0.5
50
-5


In [29]:
# How to run the square root operation - 
import math # math is the module which you are importing

In [30]:
math.sqrt(16) # 16 is the argument of the sqrt function

4.0

In [31]:
math.sqrt(A) #A=10 which we declare at begining

3.1622776601683795

In [32]:
round(math.sqrt(A))

3

In [33]:
# lets working with string 
greeting = "hello"
name = "amxwam"

In [34]:
message = greeting + name
print(message)

helloamxwam


In [35]:
name = " amxwam"
message = greeting + name
message

'hello amxwam'

In [36]:
# ================ BOOL VARIABLES AND OPERATORS ====================
4<5

True

In [37]:
10>100

False

In [38]:
# <
# >
# <=
# >=
# and
# or
# not

In [39]:
result = 4<5

In [40]:
result

True

In [41]:
type(result)

bool

In [42]:
print(type(result))

<class 'bool'>


In [43]:
result2 = 5>1

In [44]:
result2

True

In [45]:
result3 = not(5>1)

In [46]:
result3

False

In [47]:
result or result2 or result3

True

In [48]:
result2 and result3

False

In [49]:
# =================== WHILE LOOP =========================

# what is while loop why used for - lets discuss that---

# while(condition){   # checking the condition if the conditiong is true then execute the loop and it keep continue thats why it called as loop
#     executable code1                        # if the condition is false then print to code4 
#     executable code2
#     executable code3
# }
# executable code4

In [50]:
# === python is indentation based program & no need to required 
# very important you have to check the indentataion & need to maintain properly
# python there is no curly braces
# --------------------------------------------------------------

#while condition:
#    executable code1
#    executable code2
#    executable code3
#executable code4

In [51]:
num = 12
while num<11:
    print(num)
    num = num+1
print('END OF THE PROGRAM')

END OF THE PROGRAM


In [52]:
count = 13
while count<12:
    print(count)
    count = count + 1
print("End the loop")

End the loop


In [53]:
#count = 22  #how to print infinite loop
#while count>12: # 22>12
#    print(count)
#    count = count + 1
#print("End the loop")

In [54]:
# ==================== FOR LOOP ==============================

# i define as iteration
for i in range(2):  # while loop we check the condition
    print('Hello python')

Hello python
Hello python


In [55]:
for i in range(5):
    print("Hello python:", i)
    print('welcome to amxwam')
    print('hi')

Hello python: 0
welcome to amxwam
hi
Hello python: 1
welcome to amxwam
hi
Hello python: 2
welcome to amxwam
hi
Hello python: 3
welcome to amxwam
hi
Hello python: 4
welcome to amxwam
hi


In [56]:
for i in range(7):
    print("Hello python:", i)

Hello python: 0
Hello python: 1
Hello python: 2
Hello python: 3
Hello python: 4
Hello python: 5
Hello python: 6


In [57]:
#Another way
mylist = [10,100,1000,2000]

In [58]:
mylist

[10, 100, 1000, 2000]

In [59]:
for j in mylist:
    print('jj is equal to :', j)

jj is equal to : 10
jj is equal to : 100
jj is equal to : 1000
jj is equal to : 2000


In [60]:
range(5)  #very quick way to creat a set of 5 numbers

range(0, 5)

In [61]:
list(range(5)) #what actually range 5 does

[0, 1, 2, 3, 4]

In [62]:
# ================= IF STATEMENT ======================
# -----(-2),(-1),(0),(1),(2)------------

import numpy as np # numpy is package is a scientific computation
from numpy.random import randn

In [63]:
randn()

-0.5007002694509514

In [64]:
# -----(-2),(-1),(0),(1),(2)------------

x = randn()
if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
print(x)
#print(answer) 

-1.3223162531101957


In [65]:
# -----(-2),(-1),(0),(1),(2)------------

answer = None
x = randn()
if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
print(x)
print(answer) 

0.2828452741338107
None


In [66]:
# ========== IF-ELSE STATEMENT ====================
# -----(-2),(-1),(0),(1),(2)------------

answer = None
x = randn() 
if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
else:
    answer = "Less then 1"
print(x)
print(answer) 

-1.161159623977289
Less then 1


In [67]:
# -----(-2),(-1),(0),(1),(2)------------

#================ NESTED STATEMENTS / CHAIN STATEMENT =======================

answer = None
x = randn()

if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
else:
    if x >= -1:
        answer = "Between -1 and 1"
    else:
        answer = "Less then -1"
        
print(x)
print(answer) 

1.8891377586683917
Greater then 1


In [68]:
# -----(-2),(-1),(0),(1),(2)------------

#================ ELIF STATEMENT =======================

answer = None
x = randn()

if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
elif x >= -1:
        answer = "Between -1 and 1"
else:
        answer = "Less then -1"
        
print(x)
print(answer) 

1.3673696629929395
Greater then 1


In [69]:
# ============ CODE INDENTATION IN PYTHON =================

# -----(-2),(-1),(0),(1),(2)------------

#================ ELIF STATEMENT =======================

answer = None
x = randn()

if x>1:   # if is the keyword then use condition & if the condition is true then code got executed and keep going down
    answer = "Greater then 1"
elif x >= -1:
        answer = "Between -1 and 1"
else:
        answer = "Less then -1"
        print('Aspired datascientist')
print('Aspired Datascientist')
print(x)
print(answer) 

Aspired Datascientist
1.2415306841658893
Greater then 1


### what we learned so far -
1.Type of variable
2.Using variable
3.Logical variable and operator
4.while loop
5.For loop
6.if statement, if _ else statement, elif statement
7.random variables: randn()
8.numpy 

### Fundamentals of python which are used in datascience - 

In [70]:
# List - ordered sequeence of elements & always start with 0
# you can decleare the mixed datatype variables
# List closed in [] bracket

MyFirstList = [5, 50, 67, 2020]

In [71]:
MyFirstList

[5, 50, 67, 2020]

In [72]:
type(MyFirstList)

list

In [73]:
MysecondList = [2, 5.0,'AMXWAM',True,40+67j] #multiple datatypes you can declared in the list

In [74]:
MysecondList

[2, 5.0, 'AMXWAM', True, (40+67j)]

In [75]:
type(MysecondList)

list

In [76]:
amx = ['how are you?',55, (3,4,5)] #list inside the list

In [77]:
amx

['how are you?', 55, (3, 4, 5)]

In [78]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana'] 

In [79]:
fruits.count('apple')

2

In [80]:
range(15)

range(0, 15)

In [81]:
list(range(15))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [82]:
x = [1,2,3,4,5,6,7]
x

[1, 2, 3, 4, 5, 6, 7]

In [83]:
y = list(range(8)) 

In [84]:
y

[0, 1, 2, 3, 4, 5, 6, 7]

In [85]:
z = list(range(1,8))

In [86]:
z

[1, 2, 3, 4, 5, 6, 7]

In [87]:
a1 = list(range(5,8))
a1

[5, 6, 7]

In [88]:
a2 = list(range(100,120)) 
a2

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119]

In [89]:
a3 = list(range(10,20)) # 10 form right 20-1
a3

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [90]:
a4 = list(range(10,20,3)) # adding 3 steps from 10 to 20

In [91]:
a4

[10, 13, 16, 19]

In [92]:
xx = list(range(1,5,2))

In [93]:
xx

[1, 3]

In [94]:
a5 = list(range(20,40,5))
a5

[20, 25, 30, 35]

In [95]:
# Now we can check how to read information from the list
w = ['a','e','i','o','u']

In [96]:
w

['a', 'e', 'i', 'o', 'u']

In [97]:
w[0]

'a'

In [98]:
w[1]

'e'

In [99]:
w[2]

'i'

In [100]:
#if you have more no of list so how to know how many are there

len(w)

5

In [101]:
# a,e,i,o,u
# 0,1,2,3,4
# -5,-4,-3,-2,-1

w[-4]

'e'

In [102]:
w[0]

'a'

In [103]:
# overwrite values
w

['a', 'e', 'i', 'o', 'u']

In [104]:
w[2] = 10
w[2]

10

In [105]:
w

['a', 'e', 10, 'o', 'u']

In [106]:
# slicing : operator
x = ['a', 'b', 'c', 'd', 'e' ,'f', 'g', 'h']
x

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [107]:
x[2:7] #left side part always begins with 0 but right side always have to (no.-1)// 7-1

['c', 'd', 'e', 'f', 'g']

In [108]:
x[-7:-1]

['b', 'c', 'd', 'e', 'f', 'g']

In [109]:
x[2:7]

['c', 'd', 'e', 'f', 'g']

In [110]:
x[-6:-1]

['c', 'd', 'e', 'f', 'g']

In [111]:
#advanced slicing - [_:_:_] starting,ending,step
#if you specified : one more time then you get 3 spot last step is nothing but step
x

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [112]:
x[0:8:2]

['a', 'c', 'e', 'g']

In [113]:
amxwam = ['A','B','C','D','E','F','G','H','I','J']
amxwam

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [114]:
amxwam[:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [115]:
amxwam[0:]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [116]:
amxwam[1:]

['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [117]:
amxwam[2:] #------------------------

['C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [118]:
amxwam[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [119]:
amxwam[2:7]

['C', 'D', 'E', 'F', 'G']

In [120]:
amxwam[-8:7]

['C', 'D', 'E', 'F', 'G']

In [121]:
amxwam[-8:-3]

['C', 'D', 'E', 'F', 'G']

In [122]:
# --- advanced slicing
amxwam[2:9:2]

['C', 'E', 'G', 'I']

In [123]:
amxwam[::3]

['A', 'D', 'G', 'J']

In [124]:
amxwam[::-2]

['J', 'H', 'F', 'D', 'B']

In [125]:
amxwam[6:1:-1]

['G', 'F', 'E', 'D', 'C']

In [126]:
amxwam

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']

In [127]:
amxwam[6:1:-2]

['G', 'E', 'C']

In [128]:
#Tuples -- Immutable list or immutable sequence of values

t = (10,20,90)

In [129]:
t

(10, 20, 90)

In [130]:
t[1]

20

In [131]:
#t[1]=30  #you are unable to change after declaration

In [132]:
# Functions in python 

range(20, 31)


range(20, 31)

In [133]:
list(range(20, 31))

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [134]:
mylist1 = list(range(20, 31))

In [135]:
mylist1

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [136]:
print(mylist1)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]


In [137]:
len(mylist1)

11

In [138]:
type(mylist1)

list

In [139]:
max(mylist1) 

30

In [140]:
min(mylist1)

20

In [141]:
max(1,450,234)

450

In [142]:
min(1,450,234)

1

In [143]:
# PACKAGES IN PYTHON
# PACKAGE - BOX, BLENDERS -FUNCTIONS, FRUITS - CLASS,DATA etc... 
# where & how to find the packages - github,googles Q & A query
# Install packages in anaconda prompt
# conda install package name // pip install package name
# import the packages
# from package import module
# give an example of tensorflow how to install in pip 

In [144]:
# NUMPY & ARRAY IN PYTHON
# numpy is the package you have to import 
# list is similar like to array
# numpy is also inbuild array in python

l = [23245, 27, 546, 215, -1234]
l

[23245, 27, 546, 215, -1234]

In [145]:
import numpy as np

In [146]:
a = np.array(l) # list is convert into arrays

In [147]:
a

array([23245,    27,   546,   215, -1234])

In [148]:
# what is the main difference between list & array
# you cannot create an array of different data types

b = np.array([12,455,True,'amxwam'])
b

array(['12', '455', 'True', 'amxwam'], dtype='<U11')

In [149]:
print(b)  #everything is converted into string

['12' '455' 'True' 'amxwam']


In [150]:
l  #when you select. and then tab you get list of function

[23245, 27, 546, 215, -1234]

In [151]:
l.pop()

-1234

In [152]:
l

[23245, 27, 546, 215]

In [153]:
l

[23245, 27, 546, 215]

In [154]:
a


array([23245,    27,   546,   215, -1234])

In [155]:
a.mean()

4559.8

In [156]:
a

array([23245,    27,   546,   215, -1234])

In [157]:
# slicing array

l

[23245, 27, 546, 215]

In [158]:
l[1:]

[27, 546, 215]

In [159]:
l[0:2]

[23245, 27]

In [160]:
l[::2]

[23245, 546]

In [161]:
a

array([23245,    27,   546,   215, -1234])

In [162]:
a[2:]

array([  546,   215, -1234])

In [163]:
a[2:4]

array([546, 215])

In [164]:
b 

array(['12', '455', 'True', 'amxwam'], dtype='<U11')

In [165]:
b[0]

'12'

In [166]:
c = a.copy() # when you create a copy of numpy array, modification can not be done both object array but in list it

In [167]:
a

array([23245,    27,   546,   215, -1234])

In [168]:
c

array([23245,    27,   546,   215, -1234])

In [169]:
c[0] = 0

In [170]:
c

array([    0,    27,   546,   215, -1234])

In [171]:
a

array([23245,    27,   546,   215, -1234])

In [172]:
a[0]

23245

In [173]:
a

array([23245,    27,   546,   215, -1234])

In [174]:
c

array([    0,    27,   546,   215, -1234])

In [175]:
m = [1,2,3]
m[0]

1

In [176]:
m[0]= 81

In [177]:
m

[81, 2, 3]

In [178]:
n = list.copy(m) # when you create a copy of list, modification will done both object

In [179]:
n

[81, 2, 3]

In [180]:
m

[81, 2, 3]

In [181]:
n[0]

81

In [ ]:
### PYTHOH END - 

-------